version: "3.6"

networks:
  slack_sweeper:
    external: false

services:
  slack_sweeper_db:
    container_name: slack_sweeper_db
    image: postgres
    environment:
      POSTGRES_DB: slack_sweeper_db
      POSTGRES_USER: slack_db
      POSTGRES_PASSWORD: slack_db
    networks:
      - slack_sweeper

  slack_sweeper_api:
    entrypoint: /app/etc/entrypoint.sh
    container_name: slack_sweeper_api
    image: slack_sweeper
    build:
      context: "./src/backend/"
      dockerfile: Dockerfile
    command:
      [
        "./etc/wait-for-it.sh",
        "slack_sweeper_db:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    env_file: ".env"
    ports:
      - "8000:8000"
    networks:
      - slack_sweeper
    depends_on:
      - slack_sweeper_db

  slack_sweeper_worker:
    container_name: slack_sweeper_worker
    image: slack_sweeper
    command: ["python", "manage.py", "slack_worker"]
    env_file: ".env"
    networks:
      - slack_sweeper
    depends_on:
      - slack_sweeper_api

  slack_sweeper_frontend:
    container_name: slack_sweeper_frontend
    build:
      context: "./src/frontend/"
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - slack_sweeper
    depends_on:
      - slack_sweeper_worker
