# Generated by Django 3.1.2 on 2020-10-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='whitelist',
            field=models.ManyToManyField(blank=True, to='api.SlackUser'),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='whitelists', to='api.Channel'),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='whitelists', to='api.SlackUser'),
        ),
    ]
